version: '3.8'

services:
  app:
    container_name: nestjs-user-docs-backend
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/nestjsdb
      - JWT_SECRET=your_secret_key
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # optional, for hot reload with bind mount

  db:
    image: postgres:15-alpine
    container_name: nestjs-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
