# Prometheus Configuration for Metrics Collection

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # NestJS Application metrics
  - job_name: "nestjs-app"
    static_configs:
      - targets: ["app:3000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  # PostgreSQL metrics
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s

  # Redis metrics
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s

  # Nginx metrics
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    metrics_path: "/nginx_status"
    scrape_interval: 30s

  # Elasticsearch metrics
  - job_name: "elasticsearch"
    static_configs:
      - targets: ["elasticsearch:9200"]
    metrics_path: "/_prometheus/metrics"
    scrape_interval: 30s

  # Node Exporter (if added)
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
